---

- name: restart httpd
  service: >-
    name=httpd
    state=restarted
  when: "ansible_os_family == 'RedHat'"
  
- name: restart httpd
  service: >-
    name=apache2
    state=restarted
  when: "ansible_os_family == 'Debian'"